name: Hola Mundo

on:
  push:
    branches: 
      - main

  pull_request:
      branches:
        - main   

jobs: 
  hola: 
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno
    
    steps:
      - name: imprime variables
        run: echo "Valor $MY_VAR"

    steps: 
      - name: imprime variable del repositorio
        run : echo "Valor {{ vars.MY_VARIABLE_2 }}"
  


  
    