name: Hola Mundo

on:
  push:
    branches: 
      - main

  pull_request:
      branches:
        - main   

jobs: 
  hola: 
    runs-on: ubuntu-latest

    steps: 
      - name: imprime variable del repositorio
        run : echo "Valor ${{ vars.MY_VARIABLE_2 }}"

      - name: Secreto
        run: echo "Valor del secreto ${{ secrets.MY_SECRET }}"
  


  
    