name: Hola Mundo

on:
  push:
    branches: 
      - main

  pull_request:
      branches:
        - main   

jobs: 
  hola: 
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno
    
    steps:
      - name: imprime variable
        run: echo "Valor $MY_VAR"

  


  
    